---
title: "Day 6 website updates on 4.26"
description: |
  New content in Educational Projects + Tidy Tuesday post delayed.
author:
  - name: Juan David Acosta
date: 2022-04-26
categories:
  - Website updates
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Wow, Day 6 already! Almost at the end of the first week of the website (and this blog) going live, and it does kind of feel like a blur with all the updates that have been going on. Another project has been added to the Educational Projects section of the website, and that section is starting to take shape. More projects are forthcoming, once I adapt them for public consumption and reproducibility (making sure there isn't any sensitive data that's being shared, for example). Other sections such as "Beyond the Data" should hopefully be updated by the time the weekend rolls around, which is ultimately my timeline for completing all the major sections of the website. Of course after that the website will continue to be updated with new content, especially with Tidy Tuesday weekly submissions. And that brings me to the final part of this post, which is that there is a delay in my Tidy Tuesday post for this week, so I should hopefully be posting it on Wednesday through my personal Twitter, and I'll post it here as well.

That's a wrap on today's post!
