---
title: "Undergraduate Projects"
description: |
  Original or modified projects that I have completed throughout my undergraduate studies in the Department of Statistics at the University of Toronto in Toronto, Canada. GitHub repository with all projects and files can be found here: [GitHub Repo](https://github.com/SimiDavid95/Project-Reports)
output: 
  distill::distill_article:
    toc: true
    toc-depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Money Tree Experimental Design Study

## Abstract

The money tree is a foliage plant whose defining characteristic is its palm-like leaves, which typically grow five at a time per stem. (There are mutations where more or less than five leaves grow at a time on one stem, but for the purposes of simplification, these rare cases are left out of the experiment.) The money tree, like many plants, thrives on an abundance of sunlight, regular fertilization, plenty of water, and a relatively big plant pot to grow its roots.

This study aims to identify the effect of hours exposed to direct sunlight per day, whether or not fertilizer was used, the number of waterings in a month, and the plant pot size on the number of new leaves that sprout on a money tree in a month. A replicated fractional factorial experimental design was deemed the most appropriate for the task at hand, because the factors are each divided into two (binary) levels. The design is a $2^{4-1}$ fractional factorial design, where eight runs (each with a different combination of factors) were replicated four times for a total of 32 runs. The statistical analysis consists of factorial effect estimates, which were obtained by employing a linear model, and these estimates encompass the main and interaction effects of the experiment. The Normal, Half-Normal, and Lenth plots were also analysed.

The conclusion reveals that it cannot be conclusively determined that any of the factors or interactions were significant to the growth of the money tree leaves, which goes against the initial hypothesis that the factors and interactions would be significant. A future study can run this same experiment using a modified experimental design to determine if the same conclusions will arise or not.

## Code and PDF

The code for this project, which is an Rmd file, can be found here: [Code](https://github.com/SimiDavid95/Project-Reports/blob/main/Money-Tree-Experimental-Design-Study/Money%20Tree%20Experimental%20Design%20Study.Rmd)

The PDF report for this project can be found here: [Report](https://github.com/SimiDavid95/Project-Reports/blob/main/Money-Tree-Experimental-Design-Study/Money-Tree-Experimental-Design-Study.pdf)


# Toronto Traffic During Pandemic Observational Study

## Abstract

The COVID-19 pandemic affected many aspects of our lives, including commuting habits. As lockdowns were introduced around the world, including in the Canadian city of Toronto, traffic levels dropped significantly for all modes of travel. As the pandemic progressed, there were also shifts in travel preferences, where more Torontonians preferred to get around by walking or riding a bike as opposed to driving or taking public transit.

This report investigates whether the number of cars per cyclist/pedestrian that travel through intersections in Toronto increased, decreased, or stayed the same as the pandemic progressed. Data was obtained from the Toronto Open Data portal and was cleaned, analyzed and plotted to perform exploratory data analysis. The data was fit to a multiple linear regression model in order to project the data into the future, and the model predicts that the number of cars per cyclist/pedestrian will increase given the effects of the independent variables.

The conclusion reveals that as that as the pandemic progresses, the number of cars per cyclist/pedestrian will increase, which is consistent with the lifting of lockdown and pandemic measures, which will contribute to traffic levels normalizing as more residents of Toronto go back to their in-person jobs, and more businesses either reopen or reduce their pandemic restrictions. However, the data does show that the early period of the pandemic led to a slight decrease of cars per cyclist/pedestrian, pointing to more residents preferring to either walk or bike as opposed to drive. This information can be used by the city to promote ambitions plans to expand cycling infrastructure and increase pedestrian walking spaces, in order to promote these modes of transportation and exercise.

## Code, PDF and Cleaned Data

The code for this project, which is an Rmd file, can be found here: [Code](https://github.com/SimiDavid95/Project-Reports/blob/main/Toronto-Traffic-During-Pandemic/Traffic%20in%20Toronto%20During%20Pandemic.Rmd)

The PDF report for this project can be found here: [Report](https://github.com/SimiDavid95/Project-Reports/blob/main/Toronto-Traffic-During-Pandemic/Traffic-in-Toronto-During-Pandemic.pdf)

The cleaned data for this project can be found here: [Cleaned data](https://github.com/SimiDavid95/Project-Reports/blob/main/Toronto-Traffic-During-Pandemic/cleaned_toronto_traffic_data.csv)
