---
title: "Bilingualism on Day 15"
description: |
  I have my parents to thank for being fully bilingual in English and Spanish.
author:
  - name: Juan David Acosta
date: 2022-05-05
categories:
  - Language
  - Life
  - Discussion
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

As those who know me personally know (and probably my Twitter followers as well), I am fully bilingual in English and Spanish. I was born in Colombia and lived there for around five years of my life before we packed up our bags and moved to Toronto in Canada. During my brief time in Colombia, I started picking up the basics of Spanish, up until pre-kindergarten. We then moved to Canada, and I was directly enrolled into kindergarten. I quickly embraced English, and was soon on par with the other kids. This was good news, but my parents were worried that I would start to lose my Spanish. So they only spoke to me in Spanish at home, and also enrolled me in Saturday Spanish classes for some time. Thanks to my parents' efforts, I thrived in Spanish as well, and I am proud to be fully bilingual in English and Spanish. Through elementary and high school classes I also learned some French, but today I am only at a beginner level, only able to hold a very basic conversation in French. One of my goals is to bring up my French fluency to the point where I can claim I am either intermediate or fully fluent in French. In today's world, bilingualism / multilingualism is very beneficial, and I am fortunate that this was reinforced into me by my parents. There are many programs available, as well as courses in schools and universities, that allow anyone to become fluent in another language. If you get the chance, I highly recommend learning another language.

That's a wrap on today's post!
