---
title: "Eurovision 2022 Semi-final 1 after-post on Day 20"
description: |
  A summary of my thoughts on the first semi-final of Eurovision 2022 in Turin, Italy.
author:
  - name: Juan David Acosta
date: 2022-05-10
categories:
  - Eurovision
  - Life
  - Discussion
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The first semi-final of Eurovision 2022 is now past us, and what a wave of emotions today! From my favourite phrases, "Good evening, Europe!" and "Let the Eurovision Song Contest begin!" to the acts themselves to Diodato's emotive performance of *Fai Rumore* (his 2020 entry for Italy that he performed at the empty Verona Stadium when Eurovision was cancelled due to the coronavirus pandemic) to the suspenseful results reveal where 10 of the 17 songs moved on to the final. Seven of my Top 10 countries made it (Ukraine, Netherlands, Greece, Lithuania, Norway, Iceland and Portugal), so I was pretty happy with the results. But the biggest stinger for me was that Austria did not make it, as they were my favourite entry of Semi-final 1. But alas, that's the wonderful reality of voting, you win some and you lose some. Semi-final 2 promises to be even more competitive, as that semi-final contains Sweden and Cyprus, two of my favourites to win it all. If one or both of them don't make it to the final, that would be heartbreaking. Despite this worry, it promises to be a great show like today. Is it Thursday yet?

That's a wrap on today's post!
