---
title: "Eurovision Semifinal 1 predictions"
description: |
  My Top 10 for the first semifinal of Eurovision 2022 in Turin, Italy.
author:
  - name: Juan David Acosta
date: 2022-05-09
categories:
  - Eurovision
  - Discussion
  - Life
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This week is one of my favourite weeks of the year: Eurovision week! For those who may not have heard of Eurovision until now, it is a week-long singing competition where several European countries (as well as some non-European countries) go head-to-head with three-minute songs in two semifinals and a final, and a mix of jury votes and televotes decide the winner, who then gets the chance to host the competition the following year. Since Italy won Eurovision 2021, they are hosting Eurovision 2022 in Turin. In total, 40 countries are vying for the honour of a Eurovision win, and so this week will be a special week here on the blog, where I will state my predictions and discuss what went down during the two semifinals and the final, in a sort of aftershow-style blog post.

For today's post, I will be posting my Top 10 songs of the first semifinal. These predictions were made based on both listening to the recorded versions of the songs, as well as seeing some snippets from rehearsals and the jury shows. My Top 10 for the first semifinal are:

1. Austria
2. Ukraine
3. Netherlands
4. Greece
5. Slovenia
6. Albania
7. Lithuania
8. Norway
9. Iceland
10. Portugal

Austria and Ukraine would be tied for first place in my books, but since there can't be ties, Austria leads Ukraine by just a tiny bit. My Top 10 are all songs that I consider solid entries in their own unique ways, from the absolute powerhouse that is Austria, to the incredible fusion and beautiful lyrics of Ukraine, to the retro groovy disco vibes of Slovenia, to the haunting harmonies of Iceland. I will be content with any of my Top 10 continuing on to the finals, but since Europe may vote differently, I have to brace myself for some heartbreaks during the voting.

For the interval acts, I am absolutely looking forward to Diodato's performance of *Fai Rumore*, which was his entry representing Italy in Eurovision 2020, which was eventually cancelled due to the onset of the coronavirus pandemic. Diodato's subsequent performance of *Fai Rumore* in the empty Verona Stadium during the height of COVID-19 lockdowns in Europe became the anthem of the pandemic. It is set to be a beautiful performance in Turin, and one that I am highly anticipating.

It won't be long before I hear two of my favourite phrases, "Good evening, Europe!" and "Let the Eurovision Song Contest begin!"

That's a wrap on today's post!
