---
title: "Eurovision 2022 Semi-final 2 after-post"
description: |
  A summary of my thoughts on the first semi-final of Eurovision 2022 in Turin, Italy.
author:
  - name: Juan David Acosta
date: 2022-05-12
categories:
  - Eurovision
  - Life
  - Discussion
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Today was the second semi-final of Eurovision 2022 in Turin, Italy, and what a show it was! Worlds collided when Laura Pausini and Mika sang a duet medley. Laura's music has been engrained in me because of my parents having played a bunch of her songs in the car and at home, and Mika has the song "Relax, Take It Easy" that was my jam several, several years ago. The countries today gave it their all, with several emotional ballads, experimental entries, and powerful messages. Seven of my Top 10 favourites from this semi qualified for the grand final on Saturday, but unfortunately one of my absolute favourites, Cyprus, did not make it through in a crushing upset. In contrast, I am thrilled that my beloved entries of Belgium, Sweden and Serbia have advanced to the final, where they will join a number of my other favourite entries, including the United Kingdom, which automatically advanced to the final as part of the group of Big 5 countries (along with Italy, France, Spain and Germany). The grand final is promising to be a spectacle of grand proportions, so it is good that we are given Friday as a rest day before the big conclusion to this wonderful week-long festival of music and European unity known as Eurovision. Can't wait!

That's a wrap on today's post!
