---
title: "Eurovision 2022 Grand Final Predictions"
description: |
  My Top 10 for the Grand Final of Eurovision 2022 in Turin, Italy.
author:
  - name: Juan David Acosta
date: 2022-05-13
categories:
  - Eurovision
  - Discussion
  - Life
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Oh how quickly a week goes by, especially when you're having fun! Tomorrow is the Grand Final of the Eurovision Song Contest 2022 in Turin, Italy. After two hard-fought semi-finals that saw 10 countries from each one qualify to the final, 25 countries (the 20 qualifiers plus the Big 5, which automatically qualify to the final) will battle it out in a show of European unity for the coveted prize, which is to be Europe's top song. My Top 10 for the final are the following:

1. Sweden
2. United Kingdom
3. Serbia
4. Ukraine
5. Belgium
6. Spain
7. Australia
8. Greece
9. Netherlands
10. Finland

Since this is the Grand Final, the first place in my Top 10, Sweden, is thus my favourite to win the contest. The raw emotion that Cornelia Jakobs exudes on the stage is impactful. You feel that the song resonates with you just as much as it resonates with her. The United Kingdom is a close second, with Sam Ryder sure to take off into the stratosphere with his stellar performance and staging. Serbia has grown on me more and more, and is one of the surprises in my Top 10, sitting at the number three spot when it used to rank lower before in my rank of all songs that participated in the contest. Konstrakta is a brilliant performer whose song captivates audiences with hand-washing on stage and clapping along to the catchy chorus, even if most of the general audience might not be aware of the deeper message in the song (healthcare for gig and informal workers, as well as the need for focus on mental health, in Serbia). Ukraine has one of my favourite fusions of sounds, bringing a unique mix of a ballad with Ukrainian rap. The song has taken on a whole new meaning with the war in Ukraine, and it is one of the favourites to win the contest. Belgium was an early favourite of mine, as I loved how it starts out as a ballad, and then deviates into a faster pace. Spain is what I like to call SHOW, with Chanel absolutely dominating the stage with her lively presence. Australia brings us the powerful vocal performance of the awesome Sheldon Riley, whose song is an inspiration to those of us that may have felt as outsiders, or not fully able to express ourselves due to societal and conformist pressures. Amanda represents Greece with a beautiful ballad where her vocals are the star. The Netherlands bring on the mystery vibes with S10, whose singing in Dutch mesmerizes. And finally, Finland brings the rock to the party with their high-energy performance. An honourable mention to Italy which almost made my Top 10, whose Mahmood and Blanco duet is an emotional masterpiece.

Who will win this year's Eurovision Song Contest? Only one way to find out! Saturday, here we come!

That's a wrap on today's post!
