---
title: "Summer is finally here on Day 25"
description: |
  A day out in the sun, planning for the week ahead.
author:
  - name: Juan David Acosta
date: 2022-05-15
categories:
  - Life
  - Website updates
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Today was a gorgeous day in Toronto, with sizzling temperatures that made for perfect barbecue conditions. I enjoyed the day with family, visiting my niece and nephew and having a barbecue in their backyard. It truly feels like summer has finally arrived.

In website news, this week will see me focusing on adding another school project to the website. This one is my final project from my time series analysis course, where we had to write a report based on time series data gathered from an internet source. Adding this project to my GitHub and to the website will require small modifications to remove any potentially sensitive information. I am also hoping to complete another Tidy Tuesday challenge after I've been on hiatus for a few weeks.

That's a wrap on today's post!
